/**
 * Schema Template
 *
 * Generates Zod validation schemas for VeloxTS applications.
 */

import type { GeneratedFile, TemplateContext, TemplateFunction } from '../types.js';

// ============================================================================
// Template Options
// ============================================================================

export interface SchemaOptions {
  /** Include soft delete fields (deletedAt) */
  softDelete: boolean;
  /** Include timestamp fields (createdAt, updatedAt) */
  timestamps: boolean;
  /** Generate CRUD-related schemas (create, update, patch) */
  crud: boolean;
}

// ============================================================================
// Template Functions
// ============================================================================

/**
 * Generate base schema content
 */
function generateBaseSchema(
  entity: { pascal: string; camel: string },
  options: SchemaOptions
): string {
  const { pascal, camel } = entity;
  const { softDelete, timestamps } = options;

  const timestampFields = timestamps
    ? `
  createdAt: z.date(),
  updatedAt: z.date(),`
    : '';

  const softDeleteFields = softDelete
    ? `
  deletedAt: z.date().nullable(),`
    : '';

  return `/**
 * ${pascal} Schema
 *
 * Zod validation schemas for ${pascal} entity.
 * Generated by VeloxTS CLI.
 */

import { z } from 'zod';

// ============================================================================
// Base Schema
// ============================================================================

/**
 * ${pascal} - Full entity schema with all fields
 */
export const ${camel}Schema = z.object({
  id: z.string().uuid(),
  // TODO: Add your fields here
  // name: z.string().min(1).max(255),
  // email: z.string().email(),
  // status: z.enum(['active', 'inactive', 'pending']),${timestampFields}${softDeleteFields}
});

export type ${pascal} = z.infer<typeof ${camel}Schema>;
`;
}

/**
 * Generate CRUD schemas
 */
function generateCrudSchemas(
  entity: { pascal: string; camel: string },
  options: SchemaOptions
): string {
  const { pascal, camel } = entity;
  const { softDelete, timestamps } = options;

  // Fields to omit for create schema
  const createOmitFields = ['id'];
  if (timestamps) {
    createOmitFields.push('createdAt', 'updatedAt');
  }
  if (softDelete) {
    createOmitFields.push('deletedAt');
  }

  return `
// ============================================================================
// Input Schemas (for API validation)
// ============================================================================

/**
 * Create${pascal}Input - Schema for creating a new ${pascal}
 * Omits auto-generated fields: ${createOmitFields.join(', ')}
 */
export const create${pascal}InputSchema = ${camel}Schema.omit({
  ${createOmitFields.map((f) => `${f}: true`).join(',\n  ')},
});

export type Create${pascal}Input = z.infer<typeof create${pascal}InputSchema>;

/**
 * Update${pascal}Input - Schema for full update (PUT)
 * Omits auto-generated fields: ${createOmitFields.join(', ')}
 */
export const update${pascal}InputSchema = ${camel}Schema.omit({
  ${createOmitFields.map((f) => `${f}: true`).join(',\n  ')},
});

export type Update${pascal}Input = z.infer<typeof update${pascal}InputSchema>;

/**
 * Patch${pascal}Input - Schema for partial update (PATCH)
 * All fields are optional
 */
export const patch${pascal}InputSchema = update${pascal}InputSchema.partial();

export type Patch${pascal}Input = z.infer<typeof patch${pascal}InputSchema>;

// ============================================================================
// Query Schemas
// ============================================================================

/**
 * ${pascal}IdParam - Schema for ID parameter
 */
export const ${camel}IdParamSchema = z.object({
  id: z.string().uuid(),
});

export type ${pascal}IdParam = z.infer<typeof ${camel}IdParamSchema>;

/**
 * ${pascal}ListQuery - Schema for list/search query parameters
 */
export const ${camel}ListQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
  sortBy: z.string().optional(),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
  search: z.string().optional(),
});

export type ${pascal}ListQuery = z.infer<typeof ${camel}ListQuerySchema>;

// ============================================================================
// Response Schemas
// ============================================================================

/**
 * ${pascal}Response - Single entity response
 */
export const ${camel}ResponseSchema = ${camel}Schema;

export type ${pascal}Response = z.infer<typeof ${camel}ResponseSchema>;

/**
 * ${pascal}ListResponse - Paginated list response
 */
export const ${camel}ListResponseSchema = z.object({
  data: z.array(${camel}Schema),
  meta: z.object({
    total: z.number(),
    page: z.number(),
    limit: z.number(),
    totalPages: z.number(),
  }),
});

export type ${pascal}ListResponse = z.infer<typeof ${camel}ListResponseSchema>;
`;
}

/**
 * Generate simple response schemas (non-CRUD)
 */
function generateSimpleResponseSchemas(entity: { pascal: string; camel: string }): string {
  const { pascal, camel } = entity;

  return `
// ============================================================================
// Query Schemas
// ============================================================================

/**
 * ${pascal}IdParam - Schema for ID parameter
 */
export const ${camel}IdParamSchema = z.object({
  id: z.string().uuid(),
});

export type ${pascal}IdParam = z.infer<typeof ${camel}IdParamSchema>;

// ============================================================================
// Response Schemas
// ============================================================================

/**
 * ${pascal}Response - Single entity response
 */
export const ${camel}ResponseSchema = ${camel}Schema;

export type ${pascal}Response = z.infer<typeof ${camel}ResponseSchema>;
`;
}

// ============================================================================
// Template Export
// ============================================================================

/**
 * Schema template function
 */
export const schemaTemplate: TemplateFunction<SchemaOptions> = (ctx) => {
  const base = generateBaseSchema(ctx.entity, ctx.options);

  if (ctx.options.crud) {
    return base + generateCrudSchemas(ctx.entity, ctx.options);
  }

  return base + generateSimpleResponseSchemas(ctx.entity);
};

/**
 * Get output path for schema file
 */
export function getSchemaPath(entity: { kebab: string }): string {
  return `src/schemas/${entity.kebab}.schema.ts`;
}

/**
 * Generate all files for a schema
 */
export function generateSchemaFiles(ctx: TemplateContext<SchemaOptions>): GeneratedFile[] {
  const content = schemaTemplate(ctx);

  return [
    {
      path: getSchemaPath(ctx.entity),
      content,
    },
  ];
}

/**
 * Generate post-generation instructions
 */
export function getSchemaInstructions(entityName: string, options: SchemaOptions): string {
  const schemaImports = options.crud
    ? `import {
    ${entityName}Schema,
    create${entityName}InputSchema,
    update${entityName}InputSchema,
    patch${entityName}InputSchema,
    ${entityName.charAt(0).toLowerCase() + entityName.slice(1)}IdParamSchema,
    ${entityName.charAt(0).toLowerCase() + entityName.slice(1)}ListQuerySchema,
  } from './schemas/${entityName.toLowerCase()}.schema.js';`
    : `import { ${entityName}Schema } from './schemas/${entityName.toLowerCase()}.schema.js';`;

  return `
  1. Customize the schema fields in the generated file:

     Edit the ${entityName.toLowerCase()}Schema to match your data model.

  2. Import and use in your procedures:

     ${schemaImports}

  3. Example procedure usage:

     export const get${entityName} = procedure
       .input(${entityName.charAt(0).toLowerCase() + entityName.slice(1)}IdParamSchema)
       .output(${entityName}Schema)
       .query(async ({ input, ctx }) => {
         return ctx.db.${entityName.charAt(0).toLowerCase() + entityName.slice(1)}.findUnique({
           where: { id: input.id }
         });
       });
`;
}
