/**
 * @veloxts/velox/auth - Auth package re-export
 *
 * Authentication and authorization features (coming in v1.1+)
 *
 * Use this subpath for better tree-shaking:
 * @example
 * ```typescript
 * import { createAuth, guard } from '@veloxts/velox/auth';
 * ```
 *
 * NOTE: Internal testing utilities (_resetGuardCounter) are excluded from
 * the velox meta-package. Import directly from @veloxts/auth if needed.
 */
export {
  // Types
  type AdapterAuthContext,
  type AuthConfig,
  type AuthContext,
  type AuthMiddlewareOptions,
  type BaseAuthContext,
  type GuardDefinition,
  type GuardFunction,
  type HashConfig,
  type JwtConfig,
  type NativeAuthContext,
  type PolicyAction,
  type PolicyDefinition,
  type RateLimitConfig,
  type TokenPair,
  type TokenPayload,
  type User,
  AuthError,
  // Version
  AUTH_VERSION,
  // Decoration
  AUTH_REGISTERED,
  checkDoubleRegistration,
  decorateAuth,
  getRequestAuth,
  getRequestUser,
  setRequestAuth,
  // JWT
  type TokenStore,
  createInMemoryTokenStore,
  generateTokenId,
  isValidTimespan,
  JwtManager,
  jwtManager,
  parseTimeToSeconds,
  validateTokenExpiration,
  // Enhanced Token Store
  type EnhancedTokenStore,
  type EnhancedTokenStoreOptions,
  createEnhancedTokenStore,
  DEFAULT_ALLOWED_ROLES,
  parseUserRoles,
  // Narrowing Guards
  type AuthenticatedContext,
  type InferNarrowedContext,
  type NarrowingGuard,
  type RoleNarrowedContext,
  authenticatedNarrow,
  hasRoleNarrow,
  // Password Hashing
  hashPassword,
  PasswordHasher,
  passwordHasher,
  verifyPassword,
  // Guards (excluding _resetGuardCounter)
  type GuardBuilder,
  allOf,
  anyOf,
  authenticated,
  defineGuard,
  emailVerified,
  executeGuard,
  executeGuards,
  guard,
  hasAnyPermission,
  hasPermission,
  hasRole,
  not,
  userCan,
  // Policies
  authorize,
  can,
  cannot,
  clearPolicies,
  createAdminOnlyPolicy,
  createOwnerOrAdminPolicy,
  createPolicyBuilder,
  createReadOnlyPolicy,
  definePolicy,
  getPolicy,
  registerPolicy,
  // Middleware
  authMiddleware,
  clearRateLimitStore,
  rateLimitMiddleware,
  // Rate Limiting
  type AuthRateLimitConfig,
  type AuthRateLimiter,
  type AuthRateLimiterConfig,
  authRateLimiter,
  clearAuthRateLimitStore,
  createAuthRateLimiter,
  stopAuthRateLimitCleanup,
  // Plugin
  type AuthPluginOptions,
  type AuthService,
  type JwtAuthOptions,
  authPlugin,
  defaultAuthPlugin,
  jwtAuth,
  // CSRF
  type CsrfConfig,
  type CsrfContext,
  type CsrfCookieConfig,
  type CsrfErrorCode,
  type CsrfManager,
  type CsrfMiddlewareOptions,
  type CsrfTokenConfig,
  type CsrfTokenData,
  type CsrfTokenResult,
  type CsrfValidationConfig,
  CsrfError,
  csrfManager,
  csrfMiddleware,
  // Session
  type Session,
  type SessionAuthContext,
  type SessionConfig,
  type SessionContext,
  type SessionCookieConfig,
  type SessionData,
  type SessionExpirationConfig,
  type SessionManager,
  type SessionMiddlewareOptions,
  type SessionStore,
  type StoredSession,
  inMemorySessionStore,
  sessionManager,
  sessionMiddleware,
  // Adapter System
  type AdapterHttpMethod,
  type AdapterMiddlewareContext,
  type AdapterMiddlewareOptions,
  type AdapterRoute,
  type AdapterSession,
  type AdapterSessionResult,
  type AdapterUser,
  type AuthAdapter,
  type AuthAdapterConfig,
  type AuthAdapterErrorCode,
  type AuthAdapterPluginOptions,
  type InferAdapterConfig,
  AuthAdapterError,
  BaseAuthAdapter,
  createAdapterAuthMiddleware,
  createAuthAdapterPlugin,
  defineAuthAdapter,
  isAuthAdapter,
  // BetterAuth Adapter
  type BetterAuthAdapterConfig,
  type BetterAuthApi,
  type BetterAuthHandler,
  type BetterAuthInstance,
  type BetterAuthSession,
  type BetterAuthSessionResult,
  type BetterAuthUser,
  BetterAuthAdapter,
  createBetterAuthAdapter,
  // JWT Adapter
  type JwtAdapterConfig,
  createJwtAdapter,
  JwtAdapter,
  // Password Policy
  type PasswordPolicyConfig,
  type PasswordValidationResult,
  type UserInfo,
  checkPasswordBreach,
  checkPasswordStrength,
  isCommonPassword,
  PasswordPolicy,
  PasswordStrength,
  passwordPolicy,
  // DI Providers
  authServiceProvider,
  jwtManagerProvider,
  passwordHasherProvider,
  passwordHasherProviderWithDefaults,
  registerAuthProviders,
  // DI Tokens
  AUTH_CONFIG,
  AUTH_RATE_LIMITER,
  AUTH_SERVICE,
  CSRF_CONFIG,
  HASH_CONFIG,
  JWT_CONFIG,
  JWT_MANAGER,
  PASSWORD_HASHER,
  RATE_LIMIT_CONFIG,
  SESSION_CONFIG,
  SESSION_STORE,
  TOKEN_STORE,
} from '@veloxts/auth';
