/**
 * React Flight Protocol Utilities
 *
 * Provides module resolution for React Server Components streaming.
 * Uses react-server-dom-webpack for Flight protocol implementation.
 *
 * @module @veloxts/web/rendering/flight
 */

import { readFile } from 'node:fs/promises';

/**
 * Module map for React Flight protocol.
 * Maps module IDs to their client references.
 */
export interface FlightModuleMap {
  [moduleId: string]: {
    id: string;
    chunks: string[];
    name: string;
  };
}

/**
 * Client manifest for bundled modules.
 * Generated by Vinxi during build.
 */
export interface ClientManifest {
  [moduleId: string]: {
    id: string;
    chunks: string[];
    name: string;
  };
}

/**
 * Creates a module map from a client manifest.
 *
 * In development, this can be an empty map since modules are loaded on-demand.
 * In production, this should be populated from the Vinxi build manifest.
 *
 * @param manifest - Optional client manifest from build
 * @returns Module map for React Flight
 *
 * @example
 * ```typescript
 * // Production: Load from build manifest
 * const manifest = await loadClientManifest();
 * const moduleMap = createModuleMap(manifest);
 *
 * // Development: Empty map (HMR handles resolution)
 * const devModuleMap = createModuleMap();
 * ```
 */
export function createModuleMap(manifest?: ClientManifest): FlightModuleMap {
  return manifest ?? {};
}

/**
 * Creates an empty module map for development.
 * Modules are resolved dynamically via Vinxi's HMR.
 *
 * @returns Empty module map
 *
 * @example
 * ```typescript
 * const moduleMap = createEmptyModuleMap();
 * // Use in development where HMR handles module resolution
 * ```
 */
export function createEmptyModuleMap(): FlightModuleMap {
  return {};
}

/**
 * Resolves the client manifest path based on environment.
 *
 * @returns Path to client manifest JSON, or undefined in development
 *
 * @example
 * ```typescript
 * const manifestPath = resolveClientManifest();
 * if (manifestPath) {
 *   // Production: Load manifest from file
 * } else {
 *   // Development: No manifest needed
 * }
 * ```
 */
export function resolveClientManifest(): string | undefined {
  const isDev = process.env.NODE_ENV !== 'production';

  if (isDev) {
    // Development: No manifest needed, modules loaded via HMR
    return undefined;
  }

  // Production: Vinxi generates manifest at build time
  // Location depends on Vinxi's output configuration
  return './.vinxi/manifest/client-manifest.json';
}

/**
 * Loads the client manifest if available.
 * Falls back to empty map in development.
 *
 * @returns Promise resolving to module map
 *
 * @example
 * ```typescript
 * const moduleMap = await loadClientManifest();
 * // moduleMap is ready for use with React Flight
 * ```
 */
export async function loadClientManifest(): Promise<FlightModuleMap> {
  const manifestPath = resolveClientManifest();

  if (!manifestPath) {
    return createEmptyModuleMap();
  }

  try {
    const manifestJson = await readFile(manifestPath, 'utf-8');
    const manifest = JSON.parse(manifestJson) as ClientManifest;
    return createModuleMap(manifest);
  } catch (error) {
    console.warn('[Flight] Failed to load client manifest, using empty map:', error);
    return createEmptyModuleMap();
  }
}

/**
 * Checks if a module ID represents a client component.
 * Client components are marked with "use client" directive.
 *
 * @param moduleId - Module identifier to check
 * @param moduleMap - Module map to search
 * @returns True if module is a client component
 */
export function isClientComponent(moduleId: string, moduleMap: FlightModuleMap): boolean {
  return moduleId in moduleMap;
}

/**
 * Gets the chunks for a client component.
 * Used by React Flight to load the component on the client.
 *
 * @param moduleId - Module identifier
 * @param moduleMap - Module map to search
 * @returns Array of chunk URLs, or empty array if not found
 */
export function getClientComponentChunks(moduleId: string, moduleMap: FlightModuleMap): string[] {
  const entry = moduleMap[moduleId];
  return entry?.chunks ?? [];
}
