/**
 * Print Page
 *
 * Demonstrates per-route layout configuration.
 * This page uses the minimal layout (replace mode) instead of the default root layout.
 *
 * In entry.server.tsx, this route is defined as:
 *   defineRoute('/print', PrintPage, [MinimalLayout])
 *
 * The minimal layout removes navigation, footer, and other UI elements
 * that shouldn't appear in print output.
 */

import type { PageConfig, PageProps } from '@veloxts/web';

/**
 * Per-route layout configuration
 *
 * This configuration tells the router to use MinimalLayout instead of
 * the default RootLayout. Modes available:
 *   - 'replace': Use only the specified layouts (replaces inherited)
 *   - 'append': Add layouts after inherited layouts
 *   - 'prepend': Add layouts before inherited layouts
 *   - 'inherit': Use inherited layouts (default)
 */
export const config: PageConfig = {
  layout: {
    // Note: In static routing, layouts are specified in defineRoute()
    // This config is for documentation and future dynamic routing support
    layouts: [], // Would reference MinimalLayout
    mode: 'replace',
  },
};

export default function PrintPage({ searchParams }: PageProps) {
  const title = typeof searchParams.title === 'string' ? searchParams.title : 'Document';

  return (
    <div className="print-page">
      <header className="print-header">
        <h1>{title}</h1>
        <p className="print-date">Printed: {new Date().toLocaleDateString()}</p>
      </header>

      <main className="print-content">
        <section>
          <h2>Per-Route Layout Configuration</h2>
          <p>This page uses the minimal layout instead of the default root layout.</p>
          <p>
            The minimal layout removes navigation, footer, and styling that would interfere with
            printing.
          </p>
        </section>

        <section>
          <h2>How It Works</h2>
          <p>In the route definition:</p>
          <pre>
            <code>{`defineRoute('/print', PrintPage, [MinimalLayout])`}</code>
          </pre>
          <p>The third parameter specifies the layout chain for this specific route.</p>
        </section>

        <section>
          <h2>Use Cases</h2>
          <ul>
            <li>Print-friendly document views</li>
            <li>Embedded widgets or iframes</li>
            <li>Authentication pages with different branding</li>
            <li>Landing pages with custom layouts</li>
          </ul>
        </section>
      </main>

      <footer className="print-footer">
        <p>Generated by VeloxTS Framework</p>
      </footer>
    </div>
  );
}
